# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings #########################################
# some objects to be added under website arg
  # image: img/personal-photo.JPG  # thumbnail when the hyperlink is provided in other websites (e.g. facebook)
  # favicon: img/favicon.png  # image of the browser tab icon
  
website:
  title: "Yi-Chen Li (Ethan)"                                # Your name
  description: "Yi-Chen Li (Ethan) is a master’s student in economics at NTU, interested in trade, political economy, and economic history, with broader interests in social science and intellectual history."   # A brief slogan for SEO
  google-analytics:
    tracking-id: "G-JFYLBEH0M1"   
    storage: cookies              # no cookies. !!If on, consent pop-up should be added
    anonymize-ip: true            # Detailed ip is masked  
  cookie-consent: true    # pop-up window added
  
  # navigation bar at the top of the website
  navbar:
    pinned: true
    # logo: /img/logo.png  # logo to the left of the title arg
    
    # your sub-pages
    left:
      # - text: "Projects"
      #   href: projects/index.qmd
      # - text: "Photography"
      #   href: photography/index.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "Blog"
        href: posts/
    
    # your social media handles
    right:
      - icon: envelope
        aria-label: email
        href: "mailto:ethanli.taiwan@gmail.com"  
      - icon: linkedin
        href: https://www.linkedin.com/in/yi-chen-li-a75513308
      - icon: twitter-x
        href: https://x.com/EthanLi1999
  
  

  ## Customize search widget =======================================
  search: 
    location: navbar  # put magnifier in the navbar panel
    type: textbox   # overlay: a pop-up search window whenever the magnifier is clicked. textbox: a fixed white region exists with the magnifier icon.
  
  ## Buttome panel =======================================
  ## It exists in every page. 3 sections: left, center, and right sections
  page-footer:
    left: |
      <span class="faux-block">Template by <a href="https://marvin-schmitt.com/blog/website-tutorial-quarto/">Marvin Schmitt</a> (CC BY-SA 4.0)</span>
  #   center: |
  #     <span class="faux-block"><a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">View the tutorial for this template!</a></span>
  #   right: |
  #     <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>

# Quarto Setting ###################################################
project:
  type: website     # Tell quarto this is a website project 
  output-dir: docs  # The dir of all rendered html.
  
  ## quarto preview setting =======================================
  preview: 
    port: 22222         # preview port (just for local preview)
    browser: true       # Pop-up a browser when clicking preview
    watch-inputs: true  # Automatic update if any changes are made
    navigate: true      # allow page switching whenever the link to other pages are clicked.

execute:
  freeze: auto  # auto: update html whenever its original qmd is changed. true: update html only if the user asks quarto to do so.

# Formatting ###################################################
format:
  html:
    # Import font from google (to be put in each html)
    include-in-header:
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100..900&family=Noto+Sans+KR:wght@100..900&family=Noto+Sans+TC:wght@100..900&family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    fontsize: 1.2em         # font size (global setting)
    theme: 
      - journal             # theme on https://bootswatch.com/
      - html/styles.scss
    toc: false              # Display toc or not (globally). false globbaly and true for specific page is recommended
    code-link: true         # Enable code section if any
    anchor-sections: true      # Create a linkable hash (#) after each header in an article 
    fig-cap-location: bottom   # figure caption location
    reference-location: document  # location of the footnote. margin: ref is placed in the RHS of the page
    footnotes-hover: true  # Whether the footnote is displayed when the curser is on it. 
    
    
# Language Formatting ###########################################
# set en means: (1) Search engine and the browser perceive the website as English. (2) font prioritize English (see styles.scss)

lang: en
